### ISSUE TITLE
Finalise OPFOR vehicle selection

### ISSUE THREAD

**Issue by nihilogist** [nihilogist/tactical-liberation-tanoa#1]
Need to run through the available vehicles and decide which ones to include in the OPFOR lists.

Can also add mod requests at this point.

**Comment by nihilogist** [comment]
List updated with commits 3fdb0f02316ef7a7c286926c62b0c7ace21d2a6c and a0ae1cd9b81ac753d72282b1af4c3da61255e4c9. Hopefully this should cover everything.

**Comment by DoctorTemporis** [comment]
RHS has a lot of different variants which look / function slightly different but have the same basic functionality - this is good for campaign variety because it makes visual identification more interesting for spotters etc.
I have classed the ones that fit our mission into arrays in which a selection from any 1 array would fit the same 'tactical requirement for the array' - ie if you want an unarmed HMMWV, any one from the Array of Unarmed HMMWV would do. We could just use one pick from everything, but we have the assets already in the mod pack, and it would be a bit of a shame not to give ourselves variety (since the infinite numbers of identical TIGRs in Liberation:Altis was a bit dull).

I think that as we have 8 days before mission 1, if we can work out a way to better spawn vehicles then we'd have a much better mission basis overall.

Array of  Unarmed HMMWV
Array of M2 HMMWV
Array of Mk19 HMMWV
Array of AT HMMWV
Array of Unarmed MRAP
Array of M2 MRAP
Array of Mk19 MRAP
Array of Armoured Car
Array of Unarmed APCs
Array of M2 APCs
Array of Mk19 APCs
Array of IFV
Array of Gun Systems
Array of Anti-Air IFV
Array of Artillery

**Array of   Unarmed HMMWV**
rhsusf_M_1025_w
rhsusf_M_1043_w
rhsusf_m998_w_2dr_fulltop
rhsusf_m998_w_2dr_halftop
rhsusf_m998_w_2dr
rhsusf_m998_w_4dr_fulltop
rhsusf_m998_w_4dr_halftop
rhsusf_m998_w_4dr
**Array of M2 HMMWV**
rhsusf_M_1025_w_m2
rhsusf_M_1043_w_m2
**Array of Mk19 HMMWV**
rhsusf_M_1025_w_mk19
rhsusf_M_1043_w_mk19
**Array of AT HMMWV**
rhsusf_M_1045_w
rhsusf_m996_w
**Array of Unarmed MRAP**
rhsusf_M1220_usarmy_wd
rhsusf_M1232_usarmy_wd
rhsusf_M1230a1_usarmy_wd
**Array of M2 MRAP**
rhsusf_M1220_M153_M2_usarmy_wd
rhsusf_M1220_M2_usarmy_wd
rhsusf_M1230_M2_usarmy_wd
rhsusf_M1232_M2_usarmy_wd
rhsusf_M1237_M2_usarmy_wd
**Array of Mk19 MRAP**
rhsusf_M1220_M153_MK19_usarmy_wd
rhsusf_M1220_MK19_usarmy_wd
rhsusf_M1230_MK19_usarmy_wd
rhsusf_M1232_MK19_usarmy_wd
rhsusf_M1237_MK19_usarmy_wd
**Array of Armoured Car**
rhsusf_M1117_W
rhsusf_stryker_m1126_m2_wd
**Array of Unarmed APCs**
rhsusf_m113_usarmy_unarmed
**Array of M2 APCs**
rhsusf_m113_usarmy
rhsusf_m113_usarmy_M240
**Array of Mk19 APCs**
rhsusf_m113_usarmy_MK19
**Array of IFV**
RHS_M2A2_wd
RHS_M2A2_BUSKI_WD
RHS_M2A3_wd
RHS_M2A3_BUSKI_wd
RHS_M2A3_BUSKIII_wd
**Array of Gun Systems**
B_T_AFV_Wheeled_01_up_cannon_F
**Array of Anti-Air IFV**
RHS_M6_wd
**Array of Artillery**
RHS_Stinger_AA_pod_WD
RHS_M119_WD
RHS_M252_WD

**Comment by DoctorTemporis** [comment]
This is the list of 'agreed opfor vehicles' but until the refactoring in milestone 2, many will not be used.
